application: ripl
version: 1
runtime: python
api_version: 1

handlers:  
- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon\.ico

- url: /apple-touch-icon\.png
  static_files: static/img/apple-touch-icon.png
  upload: static/img/apple-touch-icon\.png

- url: /apple-touch-icon-precomposed\.png
  static_files: static/img/apple-touch-icon-precomposed.png
  upload: static/img/apple-touch-icon-precomposed\.png

- url: /apple-touch-icon-57x57-precomposed\.png
  static_files: static/img/apple-touch-icon-57x57-precomposed.png
  upload: static/img/apple-touch-icon-57x57-precomposed\.png

- url: /apple-touch-icon-72x72-precomposed\.png
  static_files: static/img/apple-touch-icon-72x72-precomposed.png
  upload: static/img/apple-touch-icon-72x72-precomposed\.png

- url: /apple-touch-icon-114x114-precomposed\.png
  static_files: static/img/apple-touch-icon-114x114-precomposed.png
  upload: static/img/apple-touch-icon-114x114-precomposed\.png

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /crossdomain\.xml
  static_files: static/crossdomain.xml
  upload: static/crossdomain\.xml

- url: /css
  static_dir: static/css

- url: /less
  static_dir: static/less

- url: /js
  static_dir: static/js

- url: /img
  static_dir: static/img

- url: /downloads
  static_dir: static/downloads

- url: /admin/.*
  script: main.py
  login: admin

- url: .*
  script: main.py